name: Harbor Companion
version: "1.5.3"
slug: harbor_companion
description: Bridge between Harbor Fleet Manager and Home Assistant Supervisor API
url: https://github.com/avibarilan/Harbor
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
ingress: false
map:
  - data:rw
hassio_api: true
hassio_role: manager
homeassistant_api: false
options:
  harbor_token: ""
schema:
  harbor_token: str
